Update Network Rebuild

diff --git a/Network Rebuild b/Network Rebuild
--- a/Network Rebuild
+++ b/Network Rebuild
@@ -21,11 +21,12 @@ shutdown_zigbee() {
 
     GATEWAY_DIR="/home/centegix/gateway"
 
-    cd /home/centegix/gateway || {
-    echo "Failed to change directory"
-    exit 1
-}
-printf '\n'| "enter"
+    cd "$GATEWAY_DIR" || {
+        echo "Failed to change directory"
+        exit 1
+    }
+
+    echo ""
 
     # Example shutdown command placeholder
     # ./shutdown_zigbee.sh
